CREATE TABLE players (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	team_id INTEGER REFERENCES teams (id),
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	age TINYINT UNSIGNED NOT NULL,
	height TINYINT UNSIGNED NOT NULL,
	weight TINYINT UNSIGNED NOT NULL
)
